#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset


color() {
    echo -ne "\033[1;${colors[$1]}m"
}

declare -A colors=(
    ['red']=31
    ['green']=32
    ['yellow']=33
    ['blue']=34
    ['magenta']=35
    ['reset']=0
)

if [[ -n ${colors[$1]} ]]; then
    color "$1"
else
    echo "Usage: color {red |green |yellow |blue |magenta |reset}"
fi
