#!/usr/bin/env bash
# Following script outputs current cpu die temperature in milidegree-celcius, convert it to celcius and fahrenheit and display as:
#
# Celcius: 42.0 C
# Fahrenheit: 107.6 F

# Mock value for Mac (42000 millidegree celsius)
temp_millic=42000

temp_c=$(echo "scale=1; $temp_millic / 1000" | bc)

temp_f=$(echo "scale=1; ($temp_c * 9 / 5) + 32" | bc)

echo "Celsius: $temp_c C"
echo "Fahrenheit: $temp_f F"

