#!/usr/bin/env bash

# Arranges the files by grouping them into folder of their extension name
# TODO: Run this script in your downloads folder

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed"; exit 1; }
}

require fd
require egrep

declare -A special_cases=(
    ['^*\.(tar.*|tbz)$']='tar'
    ['^*\.(jpeg|jpg)$']='jpg'
    ['^*\.(htm|html)$']='html'
    ['^*\.(mp3|wav|flac)$']='audio'
    ['^*\.(mp4|mkv|avi|mov)$']='video'
    ['^*\.(doc|docx|odt)$']='documents'
    ['^*\.(pdf)$']='pdfs'
    ['^*\.(xls|xlsx|csv)$']='spreadsheets'
    ['^*\.(ppt|pptx)$']='presentations'
    ['^*\.(zip|rar|7z|tar|gz)$']='archives'
    ['^*\.(c|cpp|h|hpp|java|py|sh|js|ts)$']='code'
    ['^*\.(exe|msi|dmg|apk)$']='executables'
    ['^*\.(iso|img|bin)$']='disk_images'
    ['^*\.(log|txt|md)$']='text_files'
    ['^*\.(bak|tmp|swp)$']='backup_files'  
    ['^*\.(cfg|ini|json|xml|yaml|yml)$']='config_files' 
    ['^*\.(ttf|otf|woff|woff2)$']='fonts'  
)

fd -tf -d1 \
| while read file; do
    folder="$PWD/${file##*.}"
    for regex in "${!special_cases[@]}"; do
        (echo "$file" | egrep -q "$regex") && {
            folder="$PWD/${special_cases[$regex]}"
            break
        }
    done

    mkdir -p "$folder"
    mv "$file" "$folder"
done
