#!/usr/bin/env bash

# Issue: Implement Password Generation Functions
# Description:
# Create a function that generates passwords, The password should consist of uppercase letters, lowercase letters, numbers, and special characters. The function should take in a single argument, which is the length of the password to generate. The function should return the generated password.

read -p "Enter password length: " length

if ! [[ "$length" =~ ^[0-9]+$ ]]; then

    echo "Enter a valid number."
    exit 1

fi

password=$(tr -dc 'A-Za-z0-9!@#$%^&*' < /dev/urandom | head -c "$length")

echo "Pass: $password"