#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format
#
# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <file1> <file2> ..."
    exit 1
fi

for file in "$@"; do
    if [[ -e "$file" ]]; then
        echo "$(stat -c "%a" "$file") $file"
    else
        echo "Error: '$file' not found" >&2
    fi
done