#!/usr/bin/env bash

# TODO: Display weather of IIIT, Lucknow
# For more information see: https://wttr.in/:help
locationofweather="IIIT Lucknow"
weather=$(curl -s "wttr.in/$locationofweather?format=%C+%t+%w")

echo "Weather in $location is $weather"
