#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this

wifi_name=$(powershell.exe -command "netsh wlan show interfaces | Select-String SSID" | awk -F ':' '{print $2}' | sed 's/^[ \t]*//')


if [[ -n "$wifi_name" ]]; then
    echo "Connected to WiFi: $wifi_name"
else
    echo "Not connected to any WiFi."
fi