#!/usr/bin/env bash
set -e 

echo "Start Time: $1"
echo "End Time: $2"
echo "Output File: $3"
echo "YouTube URL: $4"

if [ -z "$4" ]; then
    echo "Error: No YouTube URL provided."
    exit 1
fi

START_TIME=$1
END_TIME=$2
OUTPUT_FILE=$3
YOUTUBE_URL=$4

yt-dlp -f best -o "temp_video.mp4" "$YOUTUBE_URL"
ffmpeg -i "temp_video.mp4" -ss "$START_TIME" -to "$END_TIME" -c copy "$OUTPUT_FILE"
rm "temp_video.mp4"

echo "Video saved as $OUTPUT_FILE"
